### ISSUE TITLE
Non root user gives error

### ISSUE THREAD

**Issue by Galileo1** [anguswilliams/helmfile-docker#1]
While running the docker file as non root user I get following error. When helm tries to add upstream repo. 

Helmfile snippet 

```
repositories:
 - name: helm-upstream
    url: https://nexus.XXX.XX.XX/list/helm-upstream
    username: {{ requiredEnv "USER" }}
    password: {{ requiredEnv "PASSWORD" }}

```
> err: helm exited with status 1:
  Error: mkdir /.config/helm/helm: permission denied
